// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
         'DefaultFirebaseOptions have not been configured for linux - '
         'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvoJ-fZaBBrDrrdGlkFkxE_uXyQJ7OvQU',
    appId: '1:202435635871:web:547b3546815d36f4e510aa',
    messagingSenderId: '202435635871',
    projectId: 'es-firebase-proj',
    authDomain: 'es-firebase-proj.firebaseapp.com',
    databaseURL: 'https://es-firebase-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'es-firebase-proj.firebasestorage.app',
    measurementId: 'G-S693NC8XH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBn_M4USXj9zdkDnfvsEzk3d8AmIEuZEM',
    appId: '1:202435635871:android:e49c0ff4e14a76bfe510aa',
    messagingSenderId: '202435635871',
    projectId: 'es-firebase-proj',
    databaseURL: 'https://es-firebase-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'es-firebase-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFt7eYcU-TwxvaBB6Mt1bJX_sww5K34U',
    appId: '1:202435635871:ios:d08ec2ea189d4a44e510aa',
    messagingSenderId: '202435635871',
    projectId: 'es-firebase-proj',
    databaseURL: 'https://es-firebase-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'es-firebase-proj.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFt7eYcU-TwxvaBB6Mt1bJX_sww5K34U',
    appId: '1:202435635871:ios:d08ec2ea189d4a44e510aa',
    messagingSenderId: '202435635871',
    projectId: 'es-firebase-proj',
    databaseURL: 'https://es-firebase-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'es-firebase-proj.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvoJ-fZaBBrDrrdGlkFkxE_uXyQJ7OvQU',
    appId: '1:202435635871:web:0c9784a14c33116de510aa',
    messagingSenderId: '202435635871',
    projectId: 'es-firebase-proj',
    authDomain: 'es-firebase-proj.firebaseapp.com',
    databaseURL: 'https://es-firebase-proj-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'es-firebase-proj.firebasestorage.app',
    measurementId: 'G-FPESM2KB27',
  );

}